# Generated by Django 4.2.30 on 2026-08-09 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_course_id_alter_coursematerial_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0003_alter_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('LECTURE', 'Lecture / Class Routine'), ('EXAM', 'Examination Schedule'), ('ASSIGNMENT', 'Assignment Deadline'), ('RESULT', 'Result Declaration'), ('HOLIDAY', 'Academic Holiday'), ('SEMINAR', 'Seminar / Conference'), ('WORKSHOP', 'Workshop / Training'), ('REGISTRATION', 'Course Registration'), ('NOTICE', 'Important Notice'), ('EVENT', 'General Academic Event')], default='EVENT', max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('target', models.CharField(choices=[('ALL', 'All Academic Users'), ('STUDENT', 'All Students'), ('TEACHER', 'All Teachers'), ('DEPARTMENT', 'Specific Department'), ('COURSE', 'Specific Course')], default='ALL', max_length=20)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_events', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_academic_events', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_events', to='departments.department')),
            ],
            options={
                'ordering': ['start_time', '-priority'],
            },
        ),
    ]
