# Generated by Django 4.2.30 on 2026-08-10 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='last_resend_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
