# Generated by Django 4.2.30 on 2026-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='material_type',
            field=models.CharField(choices=[('LECTURE_NOTES', 'Lecture Notes'), ('STUDY_NOTES', 'Study Notes'), ('PDF', 'PDF Document'), ('PRESENTATION', 'Presentation Slide (PPT/PPTX)'), ('QUESTION_PAPER', 'Question Paper / Sample Paper'), ('ASSIGNMENT_MATERIAL', 'Assignment Reference Material'), ('REFERENCE', 'Reference Reading'), ('SYLLABUS', 'Course Syllabus'), ('LAB_MATERIAL', 'Lab Manual / Lab Notes'), ('OTHER', 'Other Academic Material')], default='LECTURE_NOTES', max_length=30),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='unit_topic',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
