# Generated by Django 4.2.30 on 2026-08-09 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_id_alter_coursematerial_id'),
        ('departments', '0003_alter_department_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0002_alter_announcement_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements/attachments/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('ACADEMIC', 'Academic Notice'), ('EXAM', 'Examination'), ('ASSIGNMENT', 'Assignment'), ('ATTENDANCE', 'Attendance'), ('TIMETABLE', 'Timetable Change'), ('RESULT', 'Result Declaration'), ('COURSE', 'Course Update'), ('DEPARTMENT', 'Department Notice'), ('NOTICE', 'General Notice')], default='ACADEMIC', max_length=30),
        ),
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='courses.course'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='departments.department'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='announcement',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('EXPIRED', 'Expired')], default='PUBLISHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target',
            field=models.CharField(choices=[('ALL', 'All Academic Users'), ('STUDENT', 'All Students'), ('TEACHER', 'All Teachers'), ('DEPARTMENT', 'Specific Department'), ('COURSE', 'Specific Course')], default='ALL', max_length=20),
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
