# Generated by Django 6.0.7 on 2026-07-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
